name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required for pushing changes
      pages: write       # Required for deploying to GitHub Pages
      id-token: write    # Needed for future-proofing (OIDC tokens)

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Clean workspace
      - name: Clean Workspace
        run: |
          rm -rf padre-ginos/dist padre-ginos/node_modules

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: './padre-ginos/package-lock.json' # Explicit path to lock file
          working-directory: ./padre-ginos  


      # Step 4: Install dependencies
      - name: Install Dependencies
        working-directory: ./padre-ginos
        run: npm ci --include=dev 

      # Step 5: Build project
      - name: Build Project
        working-directory: ./padre-ginos
        run: npm run build

      # Step 6: Create .nojekyll file (to prevent GitHub Pages from ignoring files)
      - name: Create .nojekyll File
        run: echo > ./padre-ginos/dist/.nojekyll

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./padre-ginos/dist
