name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required for pushing changes
      pages: write       # Required for deploying to GitHub Pages
      id-token: write    # Needed for future-proofing (OIDC tokens)

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: padre-ginos/package-lock.json # Use relative path here

      # Step 3: Install dependencies
      - name: Install Dependencies
        working-directory: ./padre-ginos
        run: npm ci --include=dev 

      # Step 4: Build project
      - name: Build Project
        working-directory: ./padre-ginos
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      # Step 5: Create .nojekyll file (to prevent GitHub Pages from ignoring files)
      - name: Create .nojekyll File
        run: echo > ./padre-ginos/dist/.nojekyll

      # Step 6: Upload artifact for deployment
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./padre-ginos/dist

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
